"""empty message

Revision ID: 9bd4ada1f824
Revises: b809ef5c228c
Create Date: 2016-07-09 15:30:22.896575

"""

# revision identifiers, used by Alembic.
revision = '9bd4ada1f824'
down_revision = 'b809ef5c228c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time')
    ### end Alembic commands ###
