"""empty message

Revision ID: b809ef5c228c
Revises: None
Create Date: 2016-07-05 22:09:12.772978

"""

# revision identifiers, used by Alembic.
revision = 'b809ef5c228c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.Unicode(length=20), nullable=True),
    sa.Column('will_price', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('customer', sa.Unicode(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.Unicode(length=20), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('avaliable_weight', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rices_product_name'), 'rices', ['product_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rices_product_name'), table_name='rices')
    op.drop_table('rices')
    op.drop_table('orders')
    ### end Alembic commands ###
